steps:
  # Install backend dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    
  # Install frontend dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'client'
    
  # Build backend
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    
  # Build frontend
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'client'
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kortana:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/kortana:latest'
      - '.'
      
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kortana:$SHORT_SHA'
      
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/kortana:latest'
      
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktop/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kortana'
      - '--image=gcr.io/$PROJECT_ID/kortana:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'
      - '--set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest'
      
images:
  - 'gcr.io/$PROJECT_ID/kortana:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/kortana:latest'
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
